### ISSUE TITLE
Driver not found after installing Magisk 30.0

### ISSUE THREAD

**Issue by kekmacska** [WSTxda/ViPERFX_RE#17]
The issue only appeared after updating Magisk, before that it worked fine. I tried reinstalling the driver, but always driver not found pops up, and i can't click anywhere else in Vipe4fx re app. Android 15, Crdroid 11.2, Poco F5 Pro.

**Comment by lxwulf** [comment]
The bug is fixed with Magisk v30.1 at my side; try it out. 😊

**Comment by kekmacska** [comment]
For me too, sorry for  not telling it

**Comment by CaddyCXT** [comment]
started happening to me as well and magisk 30.1 didnt fix it

**Comment by Rjd973** [comment]
Android 15 Vince kitsune mask 4 same driver not found.

**Comment by SnippyStockins** [comment]
I had this same issue on Android 15 with the new Magisk. I was able to resolve by adding the Audio Modification Library module to Magisk. Download the latest version from here. Scroll down and download/install the latest version. Adds support for other audio mods as well.

https://www.pling.com/p/1981006/
